package:
  name: anaconda-split
  version: "2024.10"

build:
  number: 0

outputs:

  - name: anaconda
    build:
      string: py{{ CONDA_PY|replace(".", "") }}_{{ blas_impl }}_{{ PKG_BUILDNUM }}
      pin_depends: strict
      ignore_run_exports:
        - '*'
    requirements:
      host:
        - python
        - blas * mkl      # [blas_impl == 'mkl']
        - blas * openblas # [blas_impl == 'openblas']
      run:
        - python
        - blas * mkl      # [blas_impl == 'mkl']
        - blas * openblas # [blas_impl == 'openblas']

        # dependencies from scripts/config_AD2024.10.yaml
        - appscript 1.2.5  # [osx]
        - astropy 5.1  # [py==38]
        - astropy 5.3.4  # [py==39]
        - astropy 6.1.3  # [py>=310]
        - beautifulsoup4 4.12.3
        - black 24.8.0
        - bokeh 2.4.3  # [py==38]
        - bokeh 3.4.3  # [py==39]
        - bokeh 3.6.0  # [py>=310]
        - curl 8.9.1
        - dask 2023.4.1  # [py==38]
        - dask 2024.5.0  # [py==39]
        - dask 2024.8.2  # [py>=310]
        - datashader 0.15.1  # [(not s390x) and (py==38)]
        - datashader 0.16.3  # [(not s390x) and (py>=39)]
        - flask 3.0.3
        - gensim 4.3.3  # [(not s390x)]
        - h5py 3.11.0
        - holoviews 1.17.1  # [(not s390x) and (py==38)]
        - holoviews 1.19.1  # [(not s390x) and (py>=39)]
        - hvplot 0.10.0  # [(not s390x) and (py==38)]
        - hvplot 0.11.0  # [(not s390x) and (py>=39)]
        - imbalanced-learn 0.12.3
        - intake 2.0.7
        - ipython 8.12.2  # [py==38]
        - ipython 8.15.0  # [py==39]
        - ipython 8.27.0  # [py>=310]
        - isort 5.13.2
        - joblib 1.4.2
        - jq 1.6  # [(not s390x)]
        - jupyter 1.0.0
        - jupyterlab 4.2.5  # [(not s390x)]
        - jupyterlab-variableinspector 3.1.0  # [(not s390x)]
        - matplotlib 3.7.2  # [py==38]
        - matplotlib 3.9.2  # [py>=39]
        - matplotlib-base 3.7.2  # [py==38]
        - matplotlib-base 3.9.2  # [py>=39]
        - mypy 1.11.2
        - networkx 3.1  # [py==38]
        - networkx 3.2.1  # [py==39]
        - networkx 3.3  # [py>=310]
        - nltk 3.9.1
        - notebook 7.2.2  # [(not s390x)]
        - numba 0.58.1  # [(not s390x) and (py==38)]
        - numba 0.60.0  # [(not s390x) and (py>=39)]
        - numpy 1.24.3  # [py==38]
        - numpy 1.26.4  # [py>=39]
        - openpyxl 3.1.5
        - pandas 2.0.3  # [py==38]
        - pandas 2.2.2  # [py>=39]
        - panel 0.14.3  # [(not s390x) and (py==38)]
        - panel 1.4.4  # [(not s390x) and (py==39)]
        - panel 1.5.2  # [(not s390x) and (py>=310)]
        - pillow 10.4.0
        - pip 24.2
        - plotly 5.24.1
        - pycodestyle 2.11.1
        - pycurl 7.45.3
        - pyflakes 3.2.0
        - pylint 2.16.2
        - pyodbc 5.1.0
        - pytables 3.10.1  # [(not s390x) and (py>=310)]
        - pytables 3.8.0  # [(not s390x) and (py==38)]
        - pytables 3.9.2  # [(not s390x) and (py==39)]
        - pytest 7.4.4
        - python.app 3  # [osx]
        - pywavelets 1.4.1  # [py==38]
        - pywavelets 1.5.0  # [py==39]
        - pywavelets 1.7.0  # [py>=310]
        - pywin32 305  # [win]
        - requests 2.32.3
        - s3fs 2024.6.1
        - scikit-image 0.20.0  # [py==38]
        - scikit-image 0.24.0  # [py>=39]
        - scikit-learn 1.3.0  # [py==38]
        - scikit-learn 1.5.1  # [py>=39]
        - scipy 1.13.1  # [py>=39]
        - scipy 1.9.1  # [py==38]
        - scrapy 2.11.1  # [(not s390x)]
        - seaborn 0.13.2
        - setuptools 75.1.0
        - snowballstemmer 2.2.0
        - spyder 5.5.1  # [(not s390x)]
        - sqlalchemy 2.0.34
        - statsmodels 0.14.0  # [py==38]
        - statsmodels 0.14.2  # [py>=39]
        - streamlit 1.37.1  # [(not s390x)]
        - sympy 1.13.2
        - tabulate 0.9.0
        - urllib3 1.26.19  # [py<=39]
        - urllib3 2.2.3  # [py>=310]
        - wheel 0.44.0
        - xlwings 0.31.4  # [(((osx and arm64) or (osx and x86_64) or win) and (py==38))]
        - xlwings 0.32.1  # [(((osx and arm64) or (osx and x86_64) or win) and (py>=39))]
        
    test:
      requires:
        - {{ pin_subpackage('_anaconda_core', exact=True) }}
        # constraints to verify installability with extra packages
        - anaconda-toolbox >=4.0.15 # [not s390x]
        - faker >=25.8.0 # [py==312]
        - mlxtend >=0.23.1 # [py==312]
        - notebook >=7 # [not s390x]
        - openssl >=3
        - plotnine >=0.13.6 # [py==312]
        - prince >=0.13.0 # [py==312]
        - qrcode >=7.4.2 # [py==312]
        - squarify >=0.4.3 # [py==312]
        - textblob >=0.18.0.post0 # [py==312 and not s390x]
        - thefuzz >=0.22.1 # [py==312]
        - wordcloud >=1.9.3 # [py==312]
        
      imports:
        - pandas
      commands:
        - python --version

    about:
      home: https://www.anaconda.com/distribution
      license: BSD-3-Clause
      license_family: BSD
      license_file: EULA.txt
      summary: Simplifies package management and deployment of Anaconda
      description: |
        Anaconda is a Python distribution which includes over 400
        Python packages for science, math, engineering, and data analysis.
      doc_url: https://docs.anaconda.com/anaconda
      dev_url: https://github.com/ContinuumIO

  - name: _anaconda_depends
    build:
      string: py{{ CONDA_PY|replace(".", "") }}_{{ blas_impl }}_{{ PKG_BUILDNUM }}
      ignore_run_exports:
        - '*'
    requirements:
      host:
        - python
        - blas * mkl      # [blas_impl == 'mkl']
        - blas * openblas # [blas_impl == 'openblas']
      run:
        - python
        - blas * mkl      # [blas_impl == 'mkl']
        - blas * openblas # [blas_impl == 'openblas']

        # dependencies from scripts/config_AD2024.10.yaml
        - appscript   # [osx]
        - astropy 
        - beautifulsoup4 
        - black 
        - bokeh 
        - curl 
        - dask 
        - datashader   # [(not s390x)]
        - flask 
        - gensim   # [(not s390x)]
        - h5py 
        - holoviews   # [(not s390x)]
        - hvplot   # [(not s390x)]
        - imbalanced-learn 
        - intake 
        - ipython 
        - isort 
        - joblib 
        - jq   # [(not s390x)]
        - jupyter 
        - jupyterlab   # [(not s390x)]
        - jupyterlab-variableinspector   # [(not s390x)]
        - matplotlib 
        - matplotlib-base 
        - mypy 
        - networkx 
        - nltk 
        - notebook   # [(not s390x)]
        - numba   # [(not s390x)]
        - numpy 
        - openpyxl 
        - pandas 
        - panel   # [(not s390x)]
        - pillow 
        - pip 
        - plotly 
        - pycodestyle 
        - pycurl 
        - pyflakes 
        - pylint 
        - pyodbc 
        - pytables   # [(not s390x)]
        - pytest 
        - python.app   # [osx]
        - pywavelets 
        - pywin32   # [win]
        - requests 
        - s3fs 
        - scikit-image 
        - scikit-learn 
        - scipy 
        - scrapy   # [(not s390x)]
        - seaborn 
        - setuptools 
        - snowballstemmer 
        - spyder   # [(not s390x)]
        - sqlalchemy 
        - statsmodels 
        - streamlit   # [(not s390x)]
        - sympy 
        - tabulate 
        - urllib3 
        - wheel 
        - xlwings   # [(((osx and arm64) or (osx and x86_64) or win))]
        
    test:
      imports:
        - pandas
      commands:
        - python --version

    about:
      home: https://www.anaconda.com/distribution
      license: LicenseRef-Anaconda-End-User-License-Agreement
      license_family: Other
      license_file: EULA.txt
      summary: Simplifies package management and deployment of Anaconda
      description: |
        The same dependencies as the anaconda metapackage, without pinned versions.
        _anaconda_depends is used by anaconda custom to "unlock" the packages so
        that they can be updated after installing Anaconda Distribution.
      doc_url: https://docs.anaconda.com/anaconda
      dev_url: https://github.com/ContinuumIO


  - name: _anaconda_core
    build:
      string: py{{ CONDA_PY|replace(".", "") }}_{{ blas_impl }}_{{ PKG_BUILDNUM }}
      pin_depends: strict
      ignore_run_exports:
        - '*'
    requirements:
      host:
        - python
        - blas * mkl      # [blas_impl == 'mkl']
        - blas * openblas # [blas_impl == 'openblas']
      run:
        - python
        - blas * mkl      # [blas_impl == 'mkl']
        - blas * openblas # [blas_impl == 'openblas']

        # dependencies from scripts/config_AD2024.10.yaml
        - astropy 5.1  # [py==38]
        - astropy 5.3.4  # [py==39]
        - astropy 6.1.3  # [py>=310]
        - beautifulsoup4 4.12.3
        - bokeh 2.4.3  # [py==38]
        - bokeh 3.4.3  # [py==39]
        - bokeh 3.6.0  # [py>=310]
        - datashader 0.15.1  # [(not s390x) and (py==38)]
        - datashader 0.16.3  # [(not s390x) and (py>=39)]
        - gensim 4.3.3  # [(not s390x)]
        - holoviews 1.17.1  # [(not s390x) and (py==38)]
        - holoviews 1.19.1  # [(not s390x) and (py>=39)]
        - hvplot 0.10.0  # [(not s390x) and (py==38)]
        - hvplot 0.11.0  # [(not s390x) and (py>=39)]
        - imbalanced-learn 0.12.3
        - jupyterlab 4.2.5  # [(not s390x)]
        - matplotlib-base 3.7.2  # [py==38]
        - matplotlib-base 3.9.2  # [py>=39]
        - networkx 3.1  # [py==38]
        - networkx 3.2.1  # [py==39]
        - networkx 3.3  # [py>=310]
        - nltk 3.9.1
        - notebook 7.2.2  # [(not s390x)]
        - numba 0.58.1  # [(not s390x) and (py==38)]
        - numba 0.60.0  # [(not s390x) and (py>=39)]
        - numpy 1.24.3  # [py==38]
        - numpy 1.26.4  # [py>=39]
        - pandas 2.0.3  # [py==38]
        - pandas 2.2.2  # [py>=39]
        - panel 0.14.3  # [(not s390x) and (py==38)]
        - panel 1.4.4  # [(not s390x) and (py==39)]
        - panel 1.5.2  # [(not s390x) and (py>=310)]
        - pillow 10.4.0
        - plotly 5.24.1
        - pywavelets 1.4.1  # [py==38]
        - pywavelets 1.5.0  # [py==39]
        - pywavelets 1.7.0  # [py>=310]
        - scikit-learn 1.3.0  # [py==38]
        - scikit-learn 1.5.1  # [py>=39]
        - scipy 1.13.1  # [py>=39]
        - scipy 1.9.1  # [py==38]
        - seaborn 0.13.2
        - snowballstemmer 2.2.0
        - statsmodels 0.14.0  # [py==38]
        - statsmodels 0.14.2  # [py>=39]
        - sympy 1.13.2
        - tabulate 0.9.0
        - urllib3 1.26.19  # [py<=39]
        - urllib3 2.2.3  # [py>=310]
        
    test:
      requires:
        # constraints to verify installability with extra packages
        - anaconda-toolbox >=4.0.15 # [not s390x]
        - faker >=25.8.0 # [py==312]
        - mlxtend >=0.23.1 # [py==312]
        - notebook >=7 # [not s390x]
        - openssl >=3
        - plotnine >=0.13.6 # [py==312]
        - prince >=0.13.0 # [py==312]
        - qrcode >=7.4.2 # [py==312]
        - squarify >=0.4.3 # [py==312]
        - textblob >=0.18.0.post0 # [py==312 and not s390x]
        - thefuzz >=0.22.1 # [py==312]
        - wordcloud >=1.9.3 # [py==312]
        
      imports:
        - pandas
      commands:
        - python --version

    about:
      home: https://www.anaconda.com/distribution
      license: BSD-3-Clause
      license_family: BSD
      license_file: EULA.txt
      summary: Simplifies package management and deployment of Anaconda
      description: |
        Anaconda is a Python distribution which includes over 400
        Python packages for science, math, engineering, and data analysis.
      doc_url: https://docs.anaconda.com/anaconda
      dev_url: https://github.com/ContinuumIO

  - name: __anaconda_core_depends
    build:
      string: py{{ CONDA_PY|replace(".", "") }}_{{ blas_impl }}_{{ PKG_BUILDNUM }}
      ignore_run_exports:
        - '*'
    requirements:
      host:
        - python
        - blas * mkl      # [blas_impl == 'mkl']
        - blas * openblas # [blas_impl == 'openblas']
      run:
        - python
        - blas * mkl      # [blas_impl == 'mkl']
        - blas * openblas # [blas_impl == 'openblas']

        # dependencies from scripts/config_AD2024.10.yaml
        - astropy 
        - beautifulsoup4 
        - bokeh 
        - datashader   # [(not s390x)]
        - gensim   # [(not s390x)]
        - holoviews   # [(not s390x)]
        - hvplot   # [(not s390x)]
        - imbalanced-learn 
        - jupyterlab   # [(not s390x)]
        - matplotlib-base 
        - networkx 
        - nltk 
        - notebook   # [(not s390x)]
        - numba   # [(not s390x)]
        - numpy 
        - pandas 
        - panel   # [(not s390x)]
        - pillow 
        - plotly 
        - pywavelets 
        - scikit-learn 
        - scipy 
        - seaborn 
        - snowballstemmer 
        - statsmodels 
        - sympy 
        - tabulate 
        - urllib3 
        
    test:
      imports:
        - pandas
      commands:
        - python --version

    about:
      home: https://www.anaconda.com/distribution
      license: LicenseRef-Anaconda-End-User-License-Agreement
      license_family: Other
      license_file: EULA.txt
      summary: Simplifies package management and deployment of Anaconda
      description: |
        The same dependencies as the anaconda metapackage, without pinned versions.
        __anaconda_core_depends is used by anaconda custom to "unlock" the packages so
        that they can be updated after installing Anaconda Distribution.
      doc_url: https://docs.anaconda.com/anaconda
      dev_url: https://github.com/ContinuumIO

about:
  home: https://www.anaconda.com/distribution
  license: LicenseRef-Anaconda-End-User-License-Agreement
  license_family: Other
  license_file: EULA.txt
  summary: Simplifies package management and deployment of Anaconda
  description: |
    The same dependencies as the anaconda metapackage, without pinned versions.
    _anaconda_depends is used by anaconda custom to "unlock" the packages so
    that they can be updated after installing Anaconda Distribution.
  doc_url: https://docs.anaconda.com/anaconda
  dev_url: https://github.com/ContinuumIO